Algoritmo "at_19"

Var
n:inteiro

Inicio
para n de 1 ate 100  faca
        escreva ("1")
        escreval(n)

fimpara
para n de 1 ate 100  faca
        escreva("2")
        escreval(n)
fimpara
para n de 1 ate 100  faca
        escreva("3")
        escreval(n)
fimpara
para n de 1 ate 100  faca
        escreva("4")
        escreval(n)
fimpara
para n de 1 ate 100  faca
        escreva("5")
        escreval(n)
fimpara


Fimalgoritmo